import React from "react";
import { View, Text, StyleSheet, ScrollView, TouchableOpacity } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Colors } from "@/constants/colors";
import { useColorScheme } from "@/hooks/useColorScheme";

const LAST_UPDATED = "March 2026";

export default function TermsOfServiceScreen() {
  const colorScheme = useColorScheme();
  const C = Colors[colorScheme === "dark" ? "dark" : "light"];
  const s = makeStyles(C);

  return (
    <SafeAreaView style={s.safe} edges={["top"]}>
      <View style={s.header}>
        <TouchableOpacity onPress={() => router.back()} style={s.backBtn}>
          <Ionicons name="chevron-back" size={22} color={C.primary} />
          <Text style={[s.backText, { color: C.primary }]}>Back</Text>
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
        <Text style={[s.title, { color: C.text }]}>Terms of Service</Text>
        <Text style={[s.meta, { color: C.textSecondary }]}>Last updated: {LAST_UPDATED}</Text>

        <Section title="1. Acceptance of Terms" C={C}>
          By downloading, installing, or using HaulLedger ("the App"), you agree to be bound by these
          Terms of Service. If you do not agree to these terms, do not use the App. These terms apply to
          all users of HaulLedger.
        </Section>

        <Section title="2. Description of Service" C={C}>
          HaulLedger is a financial tracking application for truck drivers. It allows users to log income,
          expenses, fuel purchases, and trips; generate reports; and export data. The App is provided as-is
          to help users organize their own financial records.
        </Section>

        <Section title="3. User Accounts" C={C}>
          {"• You must provide accurate and complete information when creating an account.\n\n"}
          {"• You are responsible for maintaining the confidentiality of your password.\n\n"}
          {"• You are responsible for all activity that occurs under your account.\n\n"}
          {"• You must be at least 18 years old to use the App.\n\n"}
          {"• You may not use another person's account without their permission."}
        </Section>

        <Section title="4. User Responsibilities" C={C}>
          {"You agree that you will not:\n\n"}
          {"• Use the App for any unlawful purpose.\n\n"}
          {"• Attempt to gain unauthorized access to any part of the App or its servers.\n\n"}
          {"• Upload any content that is fraudulent, misleading, or that you do not have the right to use.\n\n"}
          {"• Reverse-engineer, decompile, or otherwise attempt to extract the source code of the App."}
        </Section>

        <Section title="5. Data Accuracy" C={C}>
          You are solely responsible for the accuracy of the financial data, mileage logs, and other
          records you enter into the App. HaulLedger does not verify, audit, or certify the accuracy of
          any user-entered information. The App is a tracking tool — it is not a substitute for a licensed
          accountant or tax professional. Always consult a qualified professional for tax and financial advice.
        </Section>

        <Section title="6. IFTA & Tax Disclaimers" C={C}>
          The IFTA calculations and reports generated by the App are estimates based on the data you provide
          and publicly available tax rates. These estimates may not reflect your actual tax liability. You
          are solely responsible for filing accurate IFTA returns and for complying with all applicable
          tax laws. HaulLedger is not liable for any penalties, fees, or losses resulting from inaccurate
          IFTA filings.
        </Section>

        <Section title="7. Intellectual Property" C={C}>
          All content, design, code, and features of the HaulLedger App are the exclusive property of
          HaulLedger and its developers. You are granted a limited, non-exclusive, non-transferable license
          to use the App for personal, non-commercial purposes. This license does not include any right to
          copy, modify, or distribute the App.
        </Section>

        <Section title="8. Limitation of Liability" C={C}>
          To the maximum extent permitted by applicable law, HaulLedger and its developers shall not be
          liable for any indirect, incidental, special, consequential, or punitive damages — including but
          not limited to loss of profits, data loss, or business interruption — arising out of your use
          or inability to use the App, even if we have been advised of the possibility of such damages.
          Our total liability shall not exceed the amount you paid for the App in the 12 months preceding
          the claim.
        </Section>

        <Section title="9. Disclaimer of Warranties" C={C}>
          The App is provided "as is" and "as available" without warranties of any kind, express or implied.
          We do not warrant that the App will be uninterrupted, error-free, or that defects will be corrected.
          Use of the App is at your own risk.
        </Section>

        <Section title="10. Account Termination" C={C}>
          You may delete your account at any time from Settings > Account > Delete Account. We reserve the
          right to suspend or terminate accounts that violate these Terms. Upon termination, your data will
          be deleted in accordance with our Privacy Policy.
        </Section>

        <Section title="11. Changes to Terms" C={C}>
          We reserve the right to modify these Terms at any time. Changes will be indicated by the
          "Last updated" date. Your continued use of the App after changes are posted constitutes your
          acceptance of the updated Terms.
        </Section>

        <Section title="12. Governing Law" C={C}>
          These Terms shall be governed by and construed in accordance with the laws of the United States.
          Any disputes arising under these Terms shall be resolved through binding arbitration.
        </Section>

        <Section title="13. Contact" C={C}>
          {"For questions about these Terms, contact us at:\n\nEmail: support@haulledger.com"}
        </Section>

        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

function Section({ title, children, C }: { title: string; children: string; C: typeof Colors.light }) {
  const s = makeStyles(C);
  return (
    <View style={s.section}>
      <Text style={[s.sectionTitle, { color: C.text }]}>{title}</Text>
      <Text style={[s.sectionBody, { color: C.textSecondary }]}>{children}</Text>
    </View>
  );
}

function makeStyles(C: typeof Colors.light) {
  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: C.background },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 8,
    },
    backBtn: { flexDirection: "row", alignItems: "center", gap: 4 },
    backText: { fontSize: 16, fontWeight: "500" },
    content: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 40 },
    title: { fontSize: 28, fontWeight: "800", marginBottom: 4 },
    meta: { fontSize: 13, marginBottom: 24 },
    section: { marginBottom: 24 },
    sectionTitle: { fontSize: 15, fontWeight: "700", marginBottom: 8 },
    sectionBody: { fontSize: 14, lineHeight: 22 },
  });
}
